name: deploy to lambda
on: [push]

jobs:
  deploy_source:
    name: deploy lambda
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: zip file
        run: |
          ls -a
          zip sendEmail.zip sendEmail.py
      
      - name: deploy zip to lambda
        run: |
          aws lambda update-function-code \
            --function-name send-email \
            --zip-file fileb://sendEmail.zip